// Dados mockados para eventos
const mockEvents = [
  {
    id: 1,
    title: "PUC IN RIO",
    description: "Quem ainda perde uma festa da MAIOR DA CAPITAL?? Pensando em vocês, o Hellboy soltou mais uma edição da PUC IN RIO!!",
    longDescription: "PUC IN RIO é uma experiência única que combina música, diversão e a energia jovem universitária. Este ano, contamos com atrações nacionais, área VIP e muito mais.\n\nNão perca a oportunidade de vivenciar uma noite inesquecível com seus amigos da faculdade!",
    image: "https://images.sympla.com.br/63043ad1c38d1-xs.jpg",
    date: "09 de Maio de 2025",
    endDate: "09 de Maio de 2025",
    time: "21:00 - 04:00",
    location: "Em breve... - Curitiba / Paraná",
    price: 80.00,
    featured: true,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "Associação Atlética PUC-PR",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 84,
    category: "festa",
    ticketName: "Lote Principal",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 2,
    title: "Calourada 2025.1",
    description: "Calourada da UFRJ do campus de Duque de Caxias.",
    longDescription: "A maior festa de recepção aos calouros de 2025! Uma noite repleta de música, diversão e novas amizades. Venha fazer parte da família UFRJ!",
    image: "https://res.cloudinary.com/htkavmx5a/image/upload/f_auto,q_auto/peqi6lzxtpeddqvsj67s.png",
    date: "8 de Maio de 2025",
    endDate: "8 de Maio de 2025",
    time: "20:00 - 03:00",
    location: "UFRJ - Rio de Janeiro / RJ",
    price: 45.00,
    featured: false,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "DCE UFRJ",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 32,
    category: "festa",
    ticketName: "Lote 1",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 3,
    title: "BAILE DO MAGNA",
    description: "O tradicional baile da faculdade que promete agitar a noite com muita música e diversão!",
    longDescription: "Uma das festas mais aguardadas do calendário universitário. O Baile do Magna reúne estudantes de várias faculdades em uma noite épica de celebração.",
    image: "https://repositorio.santamaria.rs.gov.br/midia/2025/02/F25-126003.jpg",
    date: "15 de Maio de 2025",
    endDate: "15 de Maio de 2025",
    time: "22:00 - 05:00",
    location: "Clube Magna - São Paulo / SP",
    price: 65.00,
    featured: true,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "Magna Atlética",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 156,
    category: "festa",
    ticketName: "Lote 2",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 4,
    title: "ENGENHARIADAS PARANAENSE 2025",
    description: "O maior evento esportivo das engenharias do Paraná está chegando!",
    longDescription: "Três dias de competição, integração e muito networking entre os futuros engenheiros do estado. Modalidades: futebol, vôlei, basquete, natação e muito mais!",
    image: "https://eventos.maringa.com/storage/eventos/engenhariadas-paranaense-2025-i8591.webp",
    date: "22 de Junho de 2025",
    endDate: "24 de Junho de 2025",
    time: "08:00 - 18:00",
    location: "Centro Esportivo UTFPR - Curitiba / PR",
    price: 120.00,
    featured: false,
    ageRestriction: "Aberto a todas as idades",
    organizers: "UTFPR + Parceiros",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 89,
    category: "esporte",
    ticketName: "Pacote Completo"
  },
  {
    id: 5,
    title: "FESTA DA MEDICINA UFMG",
    description: "A festa mais aguardada do curso de medicina está de volta!",
    longDescription: "Uma noite especial para celebrar a medicina e a vida universitária. Com decoração temática hospitalar e muito humor médico!",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ4fEUt67iSwhABTVoQTd9qZ5R5MKE5Okds1Q&s",
    date: "30 de Maio de 2025",
    endDate: "30 de Maio de 2025",
    time: "21:30 - 04:00",
    location: "Espaço Mineirão - Belo Horizonte / MG",
    price: 75.00,
    featured: false,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "Atlética Medicina UFMG",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 67,
    category: "festa",
    ticketName: "Lote Único"
  },
  {
    id: 6,
    title: "INTERCOMP 2025",
    description: "Competição de programação e tecnologia entre universidades!",
    longDescription: "O maior evento de tecnologia universitária do país! Hackathon, palestras, workshops e networking com as maiores empresas de tech.",
    image: "https://www.proec.unicamp.br/wp-content/uploads/2025/02/01-ConviteCalourada-2025.jpg",
    date: "12 de Julho de 2025",
    endDate: "14 de Julho de 2025",
    time: "09:00 - 22:00",
    location: "Campus USP - São Paulo / SP",
    price: 50.00,
    featured: true,
    ageRestriction: "Aberto a todas as idades",
    organizers: "IME-USP + Tech Companies",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 234,
    category: "academico",
    ticketName: "Credencial Completa"
  },
  {
    id: 7,
    title: "FORRÓ UNIVERSITÁRIO DO NORDESTE",
    description: "O melhor do forró universitário em uma noite inesquecível!",
    longDescription: "Uma celebração da cultura nordestina com as melhores bandas de forró da região. Venha dançar e se divertir ao som do melhor forró!",
    image: "https://maniadehistoria.wordpress.com/wp-content/uploads/2019/05/27875147580004753650000.jpg?w=475",
    date: "18 de Maio de 2025",
    endDate: "18 de Maio de 2025",
    time: "20:00 - 02:00",
    location: "Centro de Convenções - Fortaleza / CE",
    price: 40.00,
    featured: false,
    ageRestriction: "Proibido menores de 16 anos",
    organizers: "Movimento Forrozeiro Universitário",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 178,
    category: "show",
    ticketName: "Lote 1"
  },
  {
    id: 8,
    title: "Lula vs Bolsonaro - Debate Político",
    description: "O melhor do forró universitário em uma noite inesquecível!",
    longDescription: "Uma celebração da cultura nordestina com as melhores bandas de forró da região. Venha dançar e se divertir ao som do melhor forró!",
    image: "https://static.poder360.com.br/2024/12/print-ia-lula-bolsonaro-natal-dez2024-848x477.jpg",
    date: "18 de Maio de 2025",
    endDate: "18 de Maio de 2025",
    time: "20:00 - 02:00",
    location: "Centro de Convenções - Fortaleza / CE",
    price: 40.00,
    featured: false,
    ageRestriction: "Proibido menores de 16 anos",
    organizers: "Movimento Forrozeiro Universitário",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 178,
    category: "show",
    ticketName: "Lote 1"
  },
  {
    id: 9,
    title: "Arraial Universitário Dourados 2025",
    description: "A maior festa junina universitária do Mato Grosso do Sul! Comidas típicas, quadrilha e shows!",
    longDescription: "Prepare sua camisa xadrez e o chapéu de palha! O Arraial Universitário de Dourados volta em 2025 com muita animação, barracas de comidas e bebidas típicas, apresentações de quadrilha das atléticas e shows com bandas de forró e sertanejo. Não fique de fora dessa festança!",
    image: "https://images.unsplash.com/photo-1529258283598-8d6fe60b27f4?w=800&h=600&fit=crop&crop=center",
    date: "14 de Junho de 2025",
    endDate: "15 de Junho de 2025",
    time: "18:00 - 03:00",
    location: "Parque de Exposições - Dourados / MS",
    price: 45.00,
    featured: true,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "DCE UFGD & Atléticas de Dourados",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 120,
    category: "festa",
    ticketName: "Ingresso Arraial",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 10,
    title: "Sunset Eletrônico Beira Mar Recife",
    description: "Curta o pôr do sol ao som dos melhores DJs da cena eletrônica nordestina.",
    longDescription: "Uma experiência única na beira mar de Recife! O Sunset Eletrônico traz DJs renomados para uma tarde e noite inesquecíveis, com muita música boa, gente bonita e a brisa do mar. Prepare-se para vibrar!",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop&crop=center",
    date: "27 de Setembro de 2025",
    endDate: "27 de Setembro de 2025",
    time: "16:00 - 23:00",
    location: "Orla de Boa Viagem (altura Barraca X) - Recife / PE",
    price: 90.00,
    featured: true,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "Recife Vibes Produções",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 250,
    category: "festa",
    ticketName: "Pista Sunset",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 11,
    title: "Cervejada dos Bixos USP Ribeirão Preto",
    description: "A tradicional cervejada de recepção aos calouros da USP RP! Open bar e atrações.",
    longDescription: "Calouros e veteranos, preparem-se! A Cervejada dos Bixos da USP Ribeirão Preto está de volta com tudo: open bar de qualidade, DJs agitando a pista e a melhor integração universitária da região.",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&h=600&fit=crop&crop=center",
    date: "22 de Agosto de 2025",
    endDate: "22 de Agosto de 2025",
    time: "17:00 - 00:00",
    location: "Espaço de Eventos Campus USP - Ribeirão Preto / SP",
    price: 60.00,
    featured: false,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "Diretório Acadêmico Farmácia-Bioquímica USP RP",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 300,
    category: "festa",
    ticketName: "Lote Promocional Bixos",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 12,
    title: "Campeonato E-Sports Inter Atléticas MG",
    description: "O maior torneio de e-sports universitário de Minas Gerais. Competições de LoL, CS e Valorant.",
    longDescription: "Mostre suas habilidades no Campeonato E-Sports Inter Atléticas de MG! Times de todo o estado competindo em League of Legends, Counter-Strike e Valorant por prêmios incríveis e o troféu de campeão. Transmissão ao vivo e área para torcida.",
    image: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=800&h=600&fit=crop&crop=center",
    date: "10 de Outubro de 2025",
    endDate: "12 de Outubro de 2025",
    time: "10:00 - 22:00",
    location: "Mineirinho Arena - Belo Horizonte / MG",
    price: 25.00,
    featured: true,
    ageRestriction: "Livre para todos os públicos",
    organizers: "Liga Mineira de E-sports Universitário (LMEU)",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 450,
    category: "esporte",
    ticketName: "Acesso Torcida",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 13,
    title: "Feira de Carreiras Tech Unicamp",
    description: "Conecte-se com as maiores empresas de tecnologia e encontre sua vaga de estágio ou trainee.",
    longDescription: "A Feira de Carreiras Tech da Unicamp é a sua oportunidade de interagir com recrutadores das principais empresas de tecnologia do país. Palestras, workshops sobre carreira e processos seletivos. Traga seu currículo!",
    image: "https://images.unsplash.com/photo-1556761175-b413da4baf72?w=800&h=600&fit=crop&crop=center",
    date: "07 de Novembro de 2025",
    endDate: "07 de Novembro de 2025",
    time: "09:00 - 18:00",
    location: "Centro de Convenções Unicamp - Campinas / SP",
    price: 0.00,
    featured: false,
    ageRestriction: "Livre para todos os públicos",
    organizers: "Instituto de Computação Unicamp & Empresas Parceiras",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 800,
    category: "academico",
    ticketName: "Inscrição Gratuita",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 14,
    title: "Show Acústico MPB na Gamboa",
    description: "Uma noite mágica com o melhor da MPB em um cenário histórico de Salvador.",
    longDescription: "Desfrute de um show acústico intimista com grandes nomes e revelações da Música Popular Brasileira. O charme da Gamboa e a brisa do mar criam o ambiente perfeito para uma noite inesquecível. Mesas limitadas.",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop&crop=center",
    date: "19 de Julho de 2025",
    endDate: "19 de Julho de 2025",
    time: "20:00 - 23:30",
    location: "Solar do Unhão - Salvador / BA",
    price: 70.00,
    featured: false,
    ageRestriction: "Livre para todos os públicos, recomendado para maiores de 16 anos",
    organizers: "Bahia Musical Produções",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 95,
    category: "show",
    ticketName: "Mesa Individual",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 15,
    title: "Congresso Nacional de Engenharia de Produção ANPEPRO",
    description: "O principal evento científico da Engenharia de Produção no Brasil. Apresentação de trabalhos e palestras.",
    longDescription: "Participe do Congresso Nacional de Engenharia de Produção (CONEPRO), organizado pela ANPEPRO. Um espaço para discussão de avanços científicos, apresentação de artigos, minicursos, workshops e networking com os principais pesquisadores e profissionais da área.",
    image: "https://images.unsplash.com/photo-1515187029135-18ee286d815b?w=800&h=600&fit=crop&crop=center",
    date: "15 de Setembro de 2025",
    endDate: "18 de Setembro de 2025",
    time: "08:00 - 19:00",
    location: "Centro de Convenções de Florianópolis - Florianópolis / SC",
    price: 350.00,
    featured: true,
    ageRestriction: "Livre para todos os públicos",
    organizers: "Associação Nacional de Pós-Graduação em Engenharia de Produção (ANPEPRO)",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 650,
    category: "academico",
    ticketName: "Inscrição Estudante",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 16,
    title: "Festa à Fantasia Halloween UFRGS",
    description: "A noite mais horripilante e divertida do ano na UFRGS! Concurso de fantasias e DJs.",
    longDescription: "Prepare sua fantasia mais criativa (ou assustadora!) para a tradicional Festa de Halloween da UFRGS. DJs tocando todos os ritmos, decoração temática e o famoso concurso de fantasias com prêmios incríveis. Open bar de poções mágicas (e outras bebidas).",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQeZ9J-Nz9NWdUcIJaaL5kBZeTGXKcPiRROGQ&s",
    date: "31 de Outubro de 2025",
    endDate: "31 de Outubro de 2025",
    time: "22:00 - 05:00",
    location: "Centro de Eventos FIERGS - Porto Alegre / RS",
    price: 85.00,
    featured: true,
    ageRestriction: "Proibido menores de 18 anos",
    organizers: "DCE UFRGS & Atléticas Parceiras",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 420,
    category: "festa",
    ticketName: "Passaporte Assombrado",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 17,
    title: "Batalha de MCs da Federal Fluminense (UFF)",
    description: "Flow, rima e improviso na Batalha de MCs mais esperada de Niterói!",
    longDescription: "A cultura hip-hop invade a UFF! A Batalha de MCs reúne os melhores rimadores da região em disputas acirradas de improviso. Inscrições abertas para MCs. Evento gratuito com muita energia e respeito.",
    image: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=800&h=600&fit=crop&crop=center",
    date: "09 de Agosto de 2025",
    endDate: "09 de Agosto de 2025",
    time: "19:00 - 23:00",
    location: "Praça da Cantareira - Niterói / RJ",
    price: 0.00,
    featured: false,
    ageRestriction: "Livre para todos os públicos",
    organizers: "Coletivo Hip-Hop UFF",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 300,
    category: "cultural",
    ticketName: "Entrada Franca",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  },
  {
    id: 18,
    title: "Festival Gastronômico Sabores do Cerrado UFG",
    description: "Descubra os sabores únicos do bioma Cerrado em pratos elaborados por chefs e estudantes de gastronomia.",
    longDescription: "Uma viagem culinária pelo Cerrado! O Festival Gastronômico da UFG apresenta pratos doces e salgados que valorizam ingredientes regionais como pequi, baru, cagaita e guariroba. Aulas show, degustações e venda de produtos artesanais.",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?w=800&h=600&fit=crop&crop=center",
    date: "04 de Outubro de 2025",
    endDate: "05 de Outubro de 2025",
    time: "11:00 - 20:00",
    location: "Centro de Cultura e Eventos Prof. Ricardo Freua Bufáiçal - UFG - Goiânia / GO",
    price: 15.00,
    featured: false,
    ageRestriction: "Livre para todos os públicos",
    organizers: "Escola de Agronomia UFG & Curso de Gastronomia UFG",
    createdBy: "organizador@cuencos.com",
    isDraft: false,
    salesCount: 550,
    category: "gastronomico",
    ticketName: "Acesso ao Festival",
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString()
  }
];

module.exports = { mockEvents };
